import Head from 'next/head';
import Link from "next/link";
import Header from "../src/components/Header/Header";


export default function Home() {
  return (
    <>
        <Head>
            <title>Школа Z-Hockey</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            <Header />
            <section className="section section-main">
                <div className="main-wrapper">
                    <Link href="#">
                        <a className="map-link">Москва, ЛД «Морозово», ул. Новоостаповская д5с2</a>
                    </Link>
                    <h1 className="h1 main-title">Групповые тренировки<br />по хоккею для детей<br />от 9 лет</h1>
                    <p className="main-text">Запишитесь на первую тренировку со скидкой 50%</p>
                </div>
            </section>
        </main>
    </>
  )
}
